name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Identify GitHub Release tag name
        # get tag name from runners environment 'GITHUB_REF_NAME' and then use bash substring
        # to strip out '+' symbol - required due to gcr not supporting this as a tag
        # name (docker hub does support it).
        # note if push is NOT triggered by tag then 'GITHUB_REF_NAME' will be the branch name.
        shell: bash
        run: |
            tag="${GITHUB_REF_NAME}" && echo "tag=${tag//+/-}" >> $GITHUB_OUTPUT
            echo "[debug] Generated tag name is '${tag}'"
            echo "tag=$tag" >> $GITHUB_OUTPUT
        id: identify_github_release_tag_name
